package Ejercicio1;

public class Cocina extends Thread {
	
	
	public Cocina() {
		
	}

	int clientes=(int)(Math.random()*1+5);
	public  void run() {
		
		for(int i=0;i<clientes;i++) {
			System.out.println("Entra un nuevo cliente");
			try {
				Thread.sleep(1000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			int preparacion=(int)(Math.random()*1+5);
			for(int x=0;x<preparacion;x++) {
				try {
					Thread.sleep(1000);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				System.out.println(this.getName()+":Preparando plato...");
			}
			System.out.println("cliente despachado");
			//se que no es lo ideal pero no he encontrado otro modo de que no me salten excepciones como con esto:
			try {
				this.wait();
			} catch (InterruptedException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			this.stop();
		}
		
		
		
		
	}
}
